/**
 * Evidence sheets.
 *
 * For each chapter, a single page listing every source it cites and every
 * distilled claim from those sources. This is the artefact you read *before*
 * writing a chapter and check *after* — the distillation, pulled back out of
 * the store and arranged by where it is needed.
 */

import type { SourceStore } from "./store.ts";
import type { FigureDefinition } from "../figures/define.ts";
import { findCitations } from "./audit.ts";
import type { Source } from "./source.ts";

export interface ChapterEvidence {
  readonly chapter: string;
  readonly sources: readonly Source[];
  readonly figureCount: number;
}

/** Group cited sources by the chapter directory the citation appears in. */
export function evidenceByChapter(store: SourceStore, figures: FigureDefinition[]): ChapterEvidence[] {
  const byChapter = new Map<string, Set<string>>();
  const figCount = new Map<string, number>();

  const chapterOf = (file: string): string => {
    const m = /(?:^|\/)((?:ch|app)\d*[a-z0-9-]*)(?:\/|\.typ$)/.exec(file);
    return m?.[1] ?? "front-and-back";
  };

  for (const c of findCitations()) {
    if (!store.byKey.has(c.key)) continue;
    (byChapter.get(chapterOf(c.file)) ?? byChapter.set(chapterOf(c.file), new Set()).get(chapterOf(c.file))!).add(c.key);
  }
  for (const f of figures) {
    figCount.set(f.chapter, (figCount.get(f.chapter) ?? 0) + 1);
    for (const key of f.sources ?? []) {
      if (!store.byKey.has(key)) continue;
      (byChapter.get(f.chapter) ?? byChapter.set(f.chapter, new Set()).get(f.chapter)!).add(key);
    }
  }

  return [...new Set([...byChapter.keys(), ...figCount.keys()])]
    .sort()
    .map((chapter) => ({
      chapter,
      sources: [...(byChapter.get(chapter) ?? [])].sort().map((k) => store.byKey.get(k)!),
      figureCount: figCount.get(chapter) ?? 0,
    }));
}

const citationLine = (s: Source): string => {
  const bits = [s.authors.length ? s.authors.join("; ") : undefined, s.year ? `(${s.year})` : undefined,
    `*${s.title}*`, s.journal, s.publisher, s.number, s.doi ? `doi:${s.doi}` : s.url];
  return bits.filter(Boolean).join(". ");
};

export function renderEvidence(store: SourceStore, figures: FigureDefinition[]): string {
  const out: string[] = [
    "# Evidence sheets",
    "",
    "Generated by `node engine/cli.ts research evidence`. One section per chapter,",
    "listing the sources it draws on and every claim distilled from them.",
    "",
  ];

  for (const { chapter, sources, figureCount } of evidenceByChapter(store, figures)) {
    out.push(`## ${chapter}`, "");
    out.push(`${sources.length} source${sources.length === 1 ? "" : "s"}, ${figureCount} figure${figureCount === 1 ? "" : "s"}.`, "");
    if (sources.length === 0) {
      out.push("> No sources cited yet.", "");
      continue;
    }
    for (const s of sources) {
      out.push(`### \`${s.key}\` — ${s.tier}`, "", citationLine(s), "", `*Why:* ${s.rationale}`, "");
      if (s.claims.length === 0) {
        out.push("- _no claims distilled yet_", "");
      } else {
        for (const c of s.claims) {
          const tags = c.tags.length ? ` _(${c.tags.join(", ")})_` : "";
          out.push(`- **[${c.confidence}]** ${c.text} — ${c.locator}${tags}`);
        }
        out.push("");
      }
    }
  }
  return out.join("\n");
}

/** A compact index of every claim in the store, for grepping while writing. */
export function renderClaimIndex(store: SourceStore): string {
  const out = ["# Claim index", ""];
  for (const s of [...store.sources].sort((a, b) => a.key.localeCompare(b.key))) {
    if (s.claims.length === 0) continue;
    out.push(`## ${s.key}`, "");
    for (const c of s.claims) out.push(`- \`${s.key}/${c.id}\` [${c.confidence}] ${c.text} (${c.locator})`);
    out.push("");
  }
  return out.join("\n");
}
