/**
 * Export the source store to Hayagriva YAML, which Typst reads natively.
 *
 * The store is the single source of truth; this file is generated into
 * `build/` and never edited by hand.
 */

import type { Source, SourceType } from "./source.ts";
import type { SourceStore } from "./store.ts";

/** Our source types mapped onto Hayagriva's entry types. */
const TYPE_MAP: Record<SourceType, string> = {
  book: "Book",
  article: "Article",
  standard: "Report",
  web: "Web",
  dataset: "Repository",
  thesis: "Thesis",
  software: "Repository",
  talk: "Misc",
  report: "Report",
};

const quote = (s: string): string => JSON.stringify(s);

const indent = (level: number): string => "  ".repeat(level);

function emit(lines: string[], level: number, key: string, value?: string | number): void {
  if (value === undefined || value === "") return;
  lines.push(`${indent(level)}${key}: ${typeof value === "number" ? value : quote(String(value))}`);
}

function entry(s: Source): string[] {
  const lines: string[] = [`${s.key}:`];
  emit(lines, 1, "type", TYPE_MAP[s.type]);
  emit(lines, 1, "title", s.title);

  if (s.authors.length === 1) {
    emit(lines, 1, "author", s.authors[0]!);
  } else if (s.authors.length > 1) {
    lines.push(`${indent(1)}author:`);
    for (const a of s.authors) lines.push(`${indent(2)}- ${quote(a)}`);
  }

  if (s.year !== undefined) emit(lines, 1, "date", s.year);
  emit(lines, 1, "publisher", s.publisher);
  emit(lines, 1, "edition", s.edition);
  emit(lines, 1, "page-range", s.pages);

  // Journals and standards bodies become the entry's parent.
  if (s.journal) {
    lines.push(`${indent(1)}parent:`);
    emit(lines, 2, "type", "Periodical");
    emit(lines, 2, "title", s.journal);
    emit(lines, 2, "volume", s.volume);
    emit(lines, 2, "issue", s.issue);
  }

  if (s.doi || s.isbn || s.number) {
    lines.push(`${indent(1)}serial-number:`);
    emit(lines, 2, "doi", s.doi);
    emit(lines, 2, "isbn", s.isbn);
    emit(lines, 2, "serial", s.number);
  }

  if (s.url) {
    lines.push(`${indent(1)}url:`);
    emit(lines, 2, "value", s.url);
    emit(lines, 2, "date", s.accessed);
  }

  return lines;
}

export function toHayagriva(store: SourceStore): string {
  const header = [
    "# Generated by `node engine/cli.ts cite sync` — do not edit.",
    "# Edit the Markdown records in research/sources/ instead.",
    "",
  ];
  const body = [...store.sources]
    .sort((a, b) => a.key.localeCompare(b.key))
    .flatMap((s) => [...entry(s), ""]);
  return [...header, ...body].join("\n");
}
