#import "/book/lib/book.typ": *
// Generated by `node engine/cli.ts proof --figures`.
#show: book.with(title: "Figure proof", author: "proof")
#chapter(none)[Figure proof sheet]

== ch01 · visible-spectrum
#fig("visible-spectrum")
#pagebreak(weak: true)

== ch02 · blackbody-spectra
#fig("blackbody-spectra")
#pagebreak(weak: true)

== ch03 · metamer-pair
#fig("metamer-pair")
#pagebreak(weak: true)

== ch04 · colour-matching-functions
#fig("colour-matching-functions")
#pagebreak(weak: true)

== ch05 · cie-1931-chromaticity
#fig("cie-1931-chromaticity")
#pagebreak(weak: true)

== ch07 · transfer-functions
#fig("transfer-functions")
#pagebreak(weak: true)

== ch08 · lightness-comparison
#fig("lightness-comparison")
#pagebreak(weak: true)

== ch10 · interpolation-spaces
#fig("interpolation-spaces")
#pagebreak(weak: true)

== ch11 · delta-e-contours
#fig("delta-e-contours")
#pagebreak(weak: true)

== ch12 · oklch-gamut-slice
#fig("oklch-gamut-slice")
#pagebreak(weak: true)

== ch15 · dither-methods
#fig("dither-methods")
#pagebreak(weak: true)

== ch18 · cvd-simulation
#fig("cvd-simulation")
#pagebreak(weak: true)
