/**
 * Figure design tokens.
 *
 * Two rules govern everything here. First, figure type must match the book's
 * type: the diagrams are set in the same faces at the same optical sizes, so a
 * figure reads as part of the page rather than as a pasted-in screenshot.
 * Second, all *furniture* — axes, rules, grids, labels — is strictly neutral
 * grey. In a book about colour, the only colour on the page should be the
 * colour under discussion.
 */

import type { Vec3 } from "../color/math.ts";
import { categoricalPalette } from "../color/palette.ts";
import { srgbToHex } from "./format.ts";
import { coveredByBodyFace } from "./fonts.ts";

/** Points, the unit the whole drawing engine works in. 1 pt = 1/72 inch. */
export const MM = 72 / 25.4;

export const theme = {
  /** Figure widths, matched to the page master in `book/lib/template.typ`. */
  widths: {
    /** The text measure: 113 mm. */
    column: 113 * MM,
    /** Text plus the side margin: 175 mm. Most diagrams want this. */
    wide: 175 * MM,
    /** The side margin alone: 56 mm, wide enough for a real diagram. */
    margin: 56 * MM,
    /** Nearly the full trim, for the big set pieces. */
    full: 181 * MM,
  },

  font: {
    /**
     * The body face. The SVG renderer resolves one family per text element, so
     * `serifFallback` is chosen automatically for any label containing a glyph
     * ET Book lacks — see `draw/fonts.ts`. Never hard-code `serif` for text
     * that might contain Greek or a combining mark; use `familyFor`.
     */
    serif: "ETBookOT",
    /** Covers the Greek, combining marks and relations ET Book does not. */
    serifFallback: "Libertinus Serif",
    mono: "JetBrainsMono NFM",
    /** Optical sizes in points, matched to 11.5 pt body text. */
    size: {
      tick: 8,
      label: 9,
      title: 9.5,
      annotation: 8.5,
      tiny: 7,
    },
  },

  /** Neutral furniture. Nothing in this block is allowed to be chromatic. */
  ink: {
    primary: "#1a1a1a",
    secondary: "#5c5c5c",
    muted: "#8a8a8a",
    rule: "#a8a8a8",
    gridStrong: "#c8c8c8",
    grid: "#e0e0e0",
    /** The lightest visible line: swatch borders and figure frames. */
    hairline: "#dcdcdc",
    paper: "#ffffff",
    panel: "#f6f5f3",
  },

  stroke: {
    hairline: 0.35,
    thin: 0.5,
    regular: 0.8,
    bold: 1.3,
    emphasis: 1.8,
  },

  /** Default padding inside a figure's bounding box. */
  pad: { top: 10, right: 14, bottom: 26, left: 32 },

  tick: { length: 3, gap: 3 },
} as const;

/**
 * The book's own categorical series palette — generated by the book's own
 * algorithm, and required to survive deuteranopia and protanopia. If §14.4's
 * method is wrong, the reader will see it in every multi-series figure.
 */
let _series: string[] | undefined;
export function seriesColors(): string[] {
  if (!_series) {
    // Parameters chosen by sweeping the hue offset for the best normal-vision
    // separation subject to surviving dichromacy: ΔE_ok ≥ 0.158 under both
    // deuteranopia and protanopia, 0.208 in normal vision.
    const p = categoricalPalette({
      count: 6,
      lightness: [0.45, 0.82],
      chromaFraction: 0.9,
      cvdSafeFor: ["deutan", "protan"],
      hueOffset: 90,
    });
    _series = p.map((c: Vec3) => srgbToHex(c));
  }
  return _series;
}

export const seriesColor = (i: number): string => {
  const s = seriesColors();
  return s[i % s.length]!;
};

/** Fixed identities for the three CMF curves, used wherever x̄ ȳ z̄ appear. */
export const cmfColors = { x: "#c0392b", y: "#1e8449", z: "#2471a3" } as const;

/**
 * The family to set a piece of figure text in.
 *
 * ET Book for anything it can draw, and the fallback for the rest, decided per
 * string from the font's own coverage rather than left to the renderer's
 * heuristics. A figure label saying `x̄(λ)` therefore comes out whole.
 */
export const familyFor = (text: string): string =>
  coveredByBodyFace(text) ? theme.font.serif : theme.font.serifFallback;
