import { defineFigure } from "../../engine/figures/define.ts";
import { Canvas } from "../../engine/draw/plot.ts";
import { theme } from "../../engine/draw/theme.ts";
import { el } from "../../engine/draw/svg.ts";
import { swatchRow } from "../../engine/figures/lib/strips.ts";
import { cvdModels, simulateRgb, type CvdType } from "../../engine/color/cvd.ts";
import { categoricalPalette, paletteSeparation } from "../../engine/color/palette.ts";
import { hexToSrgb } from "../../engine/draw/format.ts";
import type { Vec3 } from "../../engine/color/math.ts";

// The palette almost every chart library ships with, and the one this book's
// own engine generates. Same number of entries, very different outcomes.
const DEFAULT_PALETTE: Vec3[] = [
  "#e41a1c", "377eb8", "4daf4a", "984ea3", "#ff7f00", "#a65628",
].map(hexToSrgb);

const VIEWS: Array<{ type: CvdType | "normal"; label: string }> = [
  { type: "normal", label: "normal trichromacy" },
  { type: "deutan", label: "deuteranopia" },
  { type: "protan", label: "protanopia" },
  { type: "tritan", label: "tritanopia" },
];

export default defineFigure({
  id: "cvd-simulation",
  chapter: "ch18",
  title: "A common palette, and a generated one, under four kinds of vision",
  caption: `Above: a widely-used qualitative palette. Below: six colours generated by the method in
    §16.4, which searches for maximum separation measured as the *worst case* across normal vision
    and two dichromacies. Both look fine on the top row. Under deuteranopia the first palette's
    red, green and brown collapse into one another; the generated palette does not, because it was
    never allowed to. The number on the right is the smallest $Delta E_"ok"$ between any two
    entries --- the only honest summary of whether a categorical palette works.`,
  claim: "A palette is only colour-blind safe if it was optimised under simulation, not checked after.",
  sources: ["brettel-1997-computerized"],
  placement: "wide",
  render() {
    const generated = categoricalPalette({
      count: 6,
      lightness: [0.45, 0.82],
      chromaFraction: 0.9,
      cvdSafeFor: ["deutan", "protan"],
      hueOffset: 90,
    });

    const width = theme.widths.wide;
    const labelWidth = 92;
    const scoreWidth = 54;
    const swatchWidth = width - labelWidth - scoreWidth;
    const rowH = 21;
    const rowGap = 4;
    const groupGap = 26;
    const headerH = 15;

    const canvas = new Canvas(
      width,
      2 * (headerH + VIEWS.length * (rowH + rowGap)) + groupGap + 6,
    );

    const drawGroup = (title: string, palette: Vec3[], y0: number) => {
      canvas.text(0, y0 + 8, title, {
        size: theme.font.size.annotation, fill: theme.ink.primary,
      });
      VIEWS.forEach((view, i) => {
        const y = y0 + headerH + i * (rowH + rowGap);
        canvas.text(labelWidth - 8, y + rowH / 2, view.label, {
          size: theme.font.size.tiny, fill: theme.ink.secondary,
          anchor: "end", baseline: "middle",
        });
        const shown = view.type === "normal"
          ? palette
          : palette.map((c) => simulateRgb(c, view.type as CvdType));
        for (const node of swatchRow(shown, {
          x: labelWidth, y, width: swatchWidth, height: rowH, gap: 2, radius: 1.5, border: true,
        })) canvas.add(node);

        const sep = paletteSeparation(shown);
        const poor = sep < 0.08;
        canvas.text(width, y + rowH / 2, sep.toFixed(3), {
          size: theme.font.size.tiny,
          fill: poor ? theme.ink.primary : theme.ink.muted,
          anchor: "end", baseline: "middle",
          family: theme.font.mono,
          weight: poor ? "bold" : undefined,
        });
      });
    };

    const groupH = headerH + VIEWS.length * (rowH + rowGap);
    drawGroup("a common qualitative palette", DEFAULT_PALETTE, 0);
    drawGroup("generated under a worst-case CVD constraint", generated, groupH + groupGap);

    canvas.add(el("line", {
      x1: 0, x2: width, y1: groupH + groupGap - 12, y2: groupH + groupGap - 12,
      stroke: theme.ink.hairline, "stroke-width": theme.stroke.hairline,
    }));

    return canvas.document();
  },
});
